CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL, -- Donor / Recipient
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE EXTENSION IF NOT EXISTS pgcrypto;
